[build-system]
requires = [
  "setuptools>=42",
  "versioneer[toml]",
  "scikit-build",
  "cmake",
  "ninja"
]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pcsr/_version.py"
versionfile_build = "pcsr/_version.py"
tag_prefix = "v"
parentdir_prefix = "pcsr-"
