name: Python Wheels (vcpkg build)

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  python:
    name: ${{ github.workflow }} Python build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name:  Install OS tools
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install autoconf automake libtool
          fi

      - uses: lukka/get-cmake@latest
        name: Install cmake and ninja (via get-cmake)

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v11
        with:
          # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
          # The Git commit id of vcpkg to be checked out. This is only needed because we are not using a submodule.
          vcpkgGitCommitId: "c8696863d371ab7f46e213d8f5ca923c4aef2a00"
          # The vcpkg.json file, which will be part of cache key computation.
          vcpkgJsonGlob: '**/vcpkg.json'
        id: runvcpkg

      - name: Prints output of run-vcpkg's action.
        run: echo "VCPKG_ROOT=${VCPKG_ROOT}"
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install cmake setuptools scikit-build wheel 'versioneer[toml]'
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        shell: bash
        run: echo "VCPKG_ROOT=${VCPKG_ROOT}"
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # CIBW_ENVIRONMENT: "VCPKG_ROOT=${{ runner.workspace }}/vcpkg"
          # vcpkg does not support i686 nor aarch64
          CIBW_ARCHS_LINUX: "x86_64"
          # Skip musllinux builds
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BUILD: "cp310-*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          retention-days: 10
